export const searchPayload = () => ({
  start: 0,
  num_found: 9,
  numFound: 9,
  docs: [
    {
      title_suggest: "A darker shade of magic",
      edition_key: ["OL25908676M"],
      cover_i: 7410930,
      isbn: ["0765376458", "9780765376459", "9781466851375", "1466851376"],
      has_fulltext: false,
      text: [
        "OL25908676M",
        "0765376458",
        "9780765376459",
        "9781466851375",
        "1466851376",
        "Victoria Schwab",
        "OL6979295A",
        "A darker shade of magic",
        "/works/OL17332803W",
        "Tor",
        "A Darker Shade of Magic",
        "V. E. Schwab"
      ],
      author_name: ["Victoria Schwab"],
      seed: ["/books/OL25908676M", "/works/OL17332803W", "/authors/OL6979295A"],
      author_key: ["OL6979295A"],
      title: "A darker shade of magic",
      publish_date: ["2015"],
      type: "work",
      ebook_count_i: 0,
      publish_place: ["New York, USA"],
      edition_count: 1,
      key: "/works/OL17332803W",
      publisher: ["Tor"],
      language: ["eng"],
      last_modified_i: 1509325187,
      author_alternative_name: ["V. E. Schwab"],
      cover_edition_key: "OL25908676M",
      publish_year: [2015],
      first_publish_year: 2015
    },
    {
      title_suggest: "Shades of Darkness Magic Spectacle and Oth",
      edition_key: ["OL11579450M"],
      isbn: ["0948893036", "9780948893032"],
      has_fulltext: false,
      edition_count: 1,
      last_modified_i: 1303235521,
      title: "Shades of Darkness Magic Spectacle and Oth",
      author_name: ["Richard Cowper"],
      seed: ["/books/OL11579450M", "/works/OL5527173W", "/authors/OL1317574A"],
      oclc: ["16151294"],
      key: "/works/OL5527173W",
      text: [
        "OL11579450M",
        "0948893036",
        "9780948893032",
        "Richard Cowper",
        "16151294",
        "OL1317574A",
        "Shades of Darkness Magic Spectacle and Oth",
        "/works/OL5527173W"
      ],
      id_goodreads: ["2395670"],
      author_key: ["OL1317574A"],
      type: "work",
      ebook_count_i: 0
    },
    {
      title_suggest: "Shades of milk and honey",
      edition_key: ["OL24524495M"],
      isbn: ["9780765325563", "076532556X"],
      has_fulltext: false,
      text: [
        "OL24524495M",
        "9780765325563",
        "076532556X",
        "Mary Robinette Kowal",
        "471820036",
        "OL6834725A",
        "Social life and customs",
        "Conduct of life",
        "Mate selection",
        "Fiction",
        "Sisters",
        "Magic",
        "Women",
        "Shades of milk and honey",
        "England",
        "Mary Robinette Kowal",
        "/works/OL15571983W",
        "Tor",
        "2010032725",
        "19th century"
      ],
      author_name: ["Mary Robinette Kowal"],
      seed: [
        "/books/OL24524495M",
        "/works/OL15571983W",
        "/subjects/social_life_and_customs",
        "/subjects/conduct_of_life",
        "/subjects/mate_selection",
        "/subjects/sisters",
        "/subjects/magic",
        "/subjects/women",
        "/subjects/fiction",
        "/subjects/place:england",
        "/subjects/time:19th_century",
        "/authors/OL6834725A"
      ],
      oclc: ["471820036"],
      author_key: ["OL6834725A"],
      subject: [
        "Social life and customs",
        "Conduct of life",
        "Mate selection",
        "Fiction",
        "Sisters",
        "Magic",
        "Women"
      ],
      title: "Shades of milk and honey",
      publish_date: ["2010"],
      type: "work",
      ebook_count_i: 0,
      publish_place: ["New York"],
      edition_count: 1,
      key: "/works/OL15571983W",
      publisher: ["Tor"],
      language: ["eng"],
      lccn: ["2010032725"],
      last_modified_i: 1303772916,
      publish_year: [2010],
      first_publish_year: 2010,
      place: ["England"],
      time: ["19th century"]
    },
    {
      title_suggest: "Shades of milk and honey",
      edition_key: ["OL24390324M"],
      isbn: ["076532556X", "9780765325563"],
      has_fulltext: true,
      text: [
        "OL24390324M",
        "076532556X",
        "9780765325563",
        "Mary Robinette Kowal",
        "471820036",
        "shadesofmilkhone00kowa",
        "OL6834725A",
        "Social life and customs",
        "In library",
        "Conduct of life",
        "Mate selection",
        "Accessible book",
        "Fiction",
        "Protected DAISY",
        "Sisters",
        "Magic",
        "Women",
        "Shades of milk and honey",
        "/works/OL15421587W",
        "Mary Robinette Kowal",
        "Tor",
        "2010032725",
        "England",
        "19th century"
      ],
      author_name: ["Mary Robinette Kowal"],
      seed: [
        "/books/OL24390324M",
        "/works/OL15421587W",
        "/subjects/social_life_and_customs",
        "/subjects/in_library",
        "/subjects/conduct_of_life",
        "/subjects/mate_selection",
        "/subjects/accessible_book",
        "/subjects/fiction",
        "/subjects/protected_daisy",
        "/subjects/sisters",
        "/subjects/magic",
        "/subjects/women",
        "/subjects/place:england",
        "/subjects/time:19th_century",
        "/authors/OL6834725A"
      ],
      oclc: ["471820036"],
      ia: ["shadesofmilkhone00kowa"],
      author_key: ["OL6834725A"],
      subject: [
        "Social life and customs",
        "In library",
        "Conduct of life",
        "Mate selection",
        "Accessible book",
        "Fiction",
        "Protected DAISY",
        "Sisters",
        "Magic",
        "Women"
      ],
      title: "Shades of milk and honey",
      lending_identifier_s: "shadesofmilkhone00kowa",
      ia_collection_s:
        "printdisabled;americana;internetarchivebooks;delawarecountydistrictlibrary;browserlending;inlibrary",
      printdisabled_s: "OL24390324M",
      type: "work",
      ebook_count_i: 1,
      publish_place: ["New York"],
      ia_box_id: ["IA126116"],
      edition_count: 1,
      first_publish_year: 2010,
      key: "/works/OL15421587W",
      public_scan_b: false,
      publisher: ["Tor"],
      language: ["eng"],
      lccn: ["2010032725"],
      last_modified_i: 1500689263,
      lending_edition_s: "OL24390324M",
      cover_edition_key: "OL24390324M",
      publish_year: [2010],
      publish_date: ["2010"],
      place: ["England"],
      time: ["19th century"]
    },
    {
      title_suggest: "A Caress of Twilight",
      edition_key: ["OL3571203M", "OL9338526M", "OL24289593M"],
      cover_i: 209769,
      subtitle: "A Novel",
      has_fulltext: true,
      id_librarything: ["4024"],
      text: [
        "OL3571203M",
        "OL9338526M",
        "OL24289593M",
        "A Novel",
        "Laurell K. Hamilton",
        "58751322",
        "49323472",
        "430736961",
        "caresstwilight00hami",
        "caressoftwilight00hami",
        "9780307554956",
        "0345435273",
        "0345478169",
        "0307554953",
        "9780345435279",
        "9780345478160",
        "OL26995A",
        "A Caress of Twilight",
        "Magic",
        "Attempted assassination",
        "Accessible book",
        "Fiction",
        "Fantasy",
        "OverDrive",
        "Protected DAISY",
        "/works/OL461920W",
        "Laurell K. Hamilton.",
        "Random House Publishing Group",
        "Ballantine Books",
        "A caress of twilight",
        "2002090183",
        "MOONLIGHT SILVERED THE ROOM, PAINTING THE BED IN A HUNdred shades of grey, white, and black.",
        "Laurell K Hamilton",
        "Laurell Hamilton",
        "LAURELL K. HAMILTON"
      ],
      author_name: ["Laurell K. Hamilton"],
      ia_loaded_id: ["caressoftwilight00hami"],
      seed: [
        "/books/OL3571203M",
        "/books/OL9338526M",
        "/books/OL24289593M",
        "/works/OL461920W",
        "/subjects/overdrive",
        "/subjects/fantasy",
        "/subjects/fiction",
        "/subjects/protected_daisy",
        "/subjects/attempted_assassination",
        "/subjects/magic",
        "/authors/OL26995A"
      ],
      oclc: ["58751322", "49323472", "430736961"],
      ia: ["caresstwilight00hami", "caressoftwilight00hami"],
      isbn: [
        "9780307554956",
        "0345435273",
        "0345478169",
        "0307554953",
        "9780345435279",
        "9780345478160"
      ],
      author_key: ["OL26995A"],
      subject: [
        "Magic",
        "Attempted assassination",
        "Accessible book",
        "Fiction",
        "Fantasy",
        "OverDrive",
        "Protected DAISY"
      ],
      title: "A Caress of Twilight",
      ia_collection_s:
        "printdisabled;librarygenesis;china;internetarchivebooks",
      first_publish_year: 2002,
      type: "work",
      ebook_count_i: 2,
      publish_place: ["New York"],
      printdisabled_s: "OL9338526M;OL3571203M",
      ia_box_id: ["IA177001"],
      edition_count: 3,
      overdrive_s: "CD266294-CEC7-4CAA-B76C-74AAB627C1D3",
      key: "/works/OL461920W",
      id_goodreads: ["1004098", "30240"],
      public_scan_b: false,
      id_overdrive: ["CD266294-CEC7-4CAA-B76C-74AAB627C1D3"],
      publisher: ["Random House Publishing Group", "Ballantine Books"],
      language: ["eng"],
      lccn: ["2002090183"],
      last_modified_i: 1406588196,
      author_alternative_name: [
        "Laurell K Hamilton",
        "Laurell Hamilton",
        "LAURELL K. HAMILTON"
      ],
      cover_edition_key: "OL3571203M",
      first_sentence: [
        "MOONLIGHT SILVERED THE ROOM, PAINTING THE BED IN A HUNdred shades of grey, white, and black."
      ],
      publish_year: [2002, 2008, 2005],
      publish_date: ["2002", "March 15, 2005", "2008"]
    },
    {
      title_suggest: "Witchcraft, or, the art of fortune-telling unveiled",
      publish_place: ["Boston"],
      has_fulltext: false,
      language: ["eng"],
      edition_count: 2,
      edition_key: ["OL15990364M", "OL14640386M"],
      last_modified_i: 1345183297,
      title: "Witchcraft, or, the art of fortune-telling unveiled",
      subject: ["Magic", "Fortune-telling", "Magic tricks"],
      author_name: ["William Frederick Pinchbeck"],
      seed: [
        "/books/OL15990364M",
        "/books/OL14640386M",
        "/works/OL11133171W",
        "/subjects/fortune-telling",
        "/subjects/magic",
        "/subjects/magic_tricks",
        "/authors/OL4647949A"
      ],
      first_publish_year: 1805,
      publish_year: [1805, 1980],
      key: "/works/OL11133171W",
      text: [
        "OL15990364M",
        "OL14640386M",
        "William Frederick Pinchbeck",
        "OL4647949A",
        "from the low ambition of the celebrated  Mary Pitcher, to the more elevated, but equally vague pretensions of the injudicious astrologer ...",
        "from the low ambition of the celebrated Mary Pitcher, to the more elevated, but equally vague pretensions of the injudicious astrologer : delineated in a series of letters between a friend and his correspondent : comprizing [sic] arguments to prove the non-existence of spirits, philosophy of the air and fire balloons, method of preparing the gas, or inflammable air, phantasmagoria, or magick well, Italian shades, puppets, reluminating automaton, opinions on ancient oracles, a few philosophical experiments, art of balancing, remarks on prejudice : together with poetick compositions on different subjects",
        "Witchcraft, or, the art of fortune-telling unveiled",
        "by William Frederick Pinchbeck",
        "by William Frederick Pinchbeck.",
        "Magic",
        "Fortune-telling",
        "Magic tricks",
        "/works/OL11133171W",
        "Printed for the author",
        "Sine nomine",
        "Witchcraft",
        "The art of fortune-telling unveiled",
        "Witchcraft, or, The art of fortune-telling unveiled",
        "The art of fortune-telling unveiled."
      ],
      publisher: ["Printed for the author", "Sine nomine"],
      publish_date: ["1805", "1980"],
      author_key: ["OL4647949A"],
      type: "work",
      ebook_count_i: 0
    },
    {
      title_suggest: "Green-eyed envy",
      edition_key: ["OL25158581M"],
      isbn: ["0441020496", "9780441020492"],
      has_fulltext: false,
      text: [
        "OL25158581M",
        "0441020496",
        "9780441020492",
        "Kasey Mackenzie",
        "Copyright Paperback Collection (Library of Congress)",
        "679930008",
        "OL7060772A",
        "a shades of Fury novel",
        "Green-eyed envy",
        "Kasey Mackenzie",
        "Furies (Roman mythology)",
        "Magic",
        "Shapeshifting",
        "Fiction",
        "/works/OL16444092W",
        "Ace Books",
        "2011675495"
      ],
      author_name: ["Kasey Mackenzie"],
      seed: [
        "/books/OL25158581M",
        "/works/OL16444092W",
        "/subjects/furies_(roman_mythology)",
        "/subjects/magic",
        "/subjects/shapeshifting",
        "/subjects/fiction",
        "/authors/OL7060772A"
      ],
      oclc: ["679930008"],
      contributor: ["Copyright Paperback Collection (Library of Congress)"],
      author_key: ["OL7060772A"],
      subject: [
        "Furies (Roman mythology)",
        "Magic",
        "Shapeshifting",
        "Fiction"
      ],
      title: "Green-eyed envy",
      publish_date: ["2011"],
      type: "work",
      ebook_count_i: 0,
      publish_place: ["New York"],
      edition_count: 1,
      key: "/works/OL16444092W",
      publisher: ["Ace Books"],
      language: ["eng"],
      lccn: ["2011675495"],
      last_modified_i: 1325650218,
      publish_year: [2011],
      first_publish_year: 2011
    },
    {
      title_suggest: "Those wonderful moments of transitory unconsciousness",
      edition_key: ["OL20163536M"],
      cover_i: 5545047,
      has_fulltext: false,
      text: [
        "OL20163536M",
        "Diego Martinez Montano",
        "OL5921544A",
        "Those wonderful moments of transitory unconsciousness",
        "/works/OL13009267W",
        "Diego Martinez Montano.",
        "tne 3124Minerva Press",
        "Amistad\r\n\r\nIt’s been a while\r\nsince we smiled\r\ntogether\r\nand you keep learning\r\nwhile I try to forget\r\nbut there’s always\r\nsomething new to talk about\r\nsomething that will make you\r\nremember what I’ve forgotten\r\nand will make me\r\nlearn\r\nwhat you already know.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nAwakening\r\n\r\nIt had been raining for several days\r\nand the musical sound of the rain got me to sleep.\r\nNot long after I woke up and my heart was full of bliss.\r\n\r\nEverything in the room seemed to be new and bright\r\nI looked through the window and the storm had gone\r\nall of a sudden I felt so alive.\r\n\r\nI opened my eyes, the windows, the door\r\nand left for good.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nConspiracy of Silence\r\n\r\nWe give each other the eye\r\nhoping\r\nthat the message \r\nwill get through.\r\n\r\nWe are no good\r\nwith words\r\nand meanwhile\r\nTime covers with dust\r\nthe chance of  a lifetime.\r\n\r\nWe scavenge for signs,\r\nerrand smiles like love-arrows\r\nbut they’ll never manage to hit us.\r\n\r\nIn the meantime\r\nwe long ,hope\r\nand grow in despair.\r\n\r\n\r\nMy heart lets go a desperate cry\r\nand I ,\r\nI am too afraid to listen.\r\n\r\nThe truth hurts,\r\nand hurt,\r\nhurt is the last thing I need\r\nright now.\r\n\r\nEven if it came from you. \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nCupid\r\n\r\nA souvenir, \r\na broken angel\r\nrests naked on your bed.\r\n\r\nHis cracked skin\r\nreminds you\r\nof a smile long gone away.\r\n\r\nFrom his head dives a hair\r\nlike a feather,\r\nlanding softly\r\non his always alert wing.\r\n\r\nJust waiting for a sign,\r\na direction\r\nlike the winds show you the way.\r\n\r\nAnd quietly,\r\nlike a kiss is born\r\na silent good bye is muttered.\r\n\r\nTwo, only two feathers\r\nwill cover now\r\nthe hermetically closed eyes\r\nof the sleeping lover.\r\n\r\n\r\nDays\r\n\r\nSlippery snakes\r\n\t\tof Wisdom.\r\nCatch one,\r\nteach her\r\nto move\r\n\t\tslowly,\r\nto watch around,\r\n\r\ndays,\r\ntamed snakes\r\ncurious and inoffensive,\r\nunaware that nights,\r\nnights,\r\nare unscrupulous\r\neagles,\r\n\r\n\t\teagles\r\n\t\twho find their prey\r\nin slow,\r\ncurious,\r\n\t\tinoffensive\r\nsnakes.\r\n\r\nDreams\r\n\r\nIndiscriminate projections\r\nof has been\r\nnot quite are,\r\nstill to be.\r\n\r\nFairies of time,\r\nfoolish directors\r\nof an orchestra\r\nof whispers,\r\ndialogues,\r\nscreams.\r\n\r\nLost souls,\r\npast visitors of paradise,\r\ntravellers of time.\r\n\r\nThey offer you \r\nenjoyable visions\r\nwhich disturb your inner steadiness.\r\n\r\nYour eyes remain closed\r\nto the self-imposed reality,\r\nwhile the person you’ve been,\r\nnot quite are,\r\nstill to be,\r\nwakes up\r\nasking questions\r\nonly the fairies of time\r\ncan answer…\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nExodus\r\n\r\n\r\nHow long does it take\r\none man\r\nto grow up\r\nand above\r\nthe child inside.\r\n\r\n\r\nAt coffee-takes\r\nthe serene mind\r\nwill elaborate\r\ntrying to find\r\nthe right \r\nway out.\r\n\r\n\r\nThe misty lagoon,\r\na labyrinth of heavy water\r\nits thickness blinds,\r\nnowhere to go\r\nnothing much behind\r\nwhile from the other side\r\nthe faint sound of metallic chimes\r\nproposes a new start.\r\n\r\n\r\nGet out there\r\nnever come back\r\ndon’t try to try\r\ndon’t listen much.\r\n\r\n\t\t\t\t\t\t\t\t\r\nI don’t know\r\nwhere to go \r\nDestiny is written with blurry words\r\nI can’t make out\r\nwhere that voice is coming from.\r\njust let me get out\r\nof this claustrophobic sea    \r\nlet me swim with style\r\nsee me going far \r\naway\r\nfrom here.\r\n\r\n\r\nThere’s a man I used to know\r\nI learned so much from him\r\njust like watching a car\r\ndriving so fucking fast.\r\n\r\n\r\n\r\n\r\n\r\nOn the number plate \r\nI could barely read\r\n“See you later on\r\nwhen the rain comes”\r\n\r\nMaybe \r\nsince then\r\nI’ve been longing to get wet\r\nto cross the tunnel\r\nfollow the seagulls\r\nthat promise me land.\r\n\r\n\r\nA firm surface,\r\nthe Sun above my head\r\nagain\r\nI need to close my eyes\r\njust for a minute.\r\n\r\n\r\nI want to see no more\r\nI just want to listen\r\nwith my heart\r\nand hear \r\nthe mermaids singing me \r\nto sleep\r\nuntil I wake up\r\non a bed of secrets.\r\n\r\n\r\nLike the ones kept within your walls;\r\ninnocent flowers\r\nneglected by the lazy gardener\r\nwho once or twice\r\nthought it would be \r\na good idea \r\nto bring some colour \r\nto his uneventful\r\nexistence.    \r\n   \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nFriends\r\n\r\nWhenever it’s cold outside\r\nand I feel like a groom with no bride,\r\n\r\nwhen words are like a jigsaw\r\nand you say the missing ones,\r\n\r\nwhenever I need a shot of altruistic wisdom\r\nor a piece of holy bread,\r\n\r\nwhen the sound of silence\r\nspells out the word friend,\r\n\r\nyou are what I see\r\nyou are what I get\r\n\r\nbrother at thick and thin\r\nyou give the word friend a good name.\r\n\r\n\r\nGod\r\n\r\nWhat does god think,\r\nwhat does god say,\r\nin lonely moments,\r\nto whom does he pray.\r\n\r\nWhat does he see\r\nwhen he opens his eyes\r\nand looks down here.\r\n\r\nAre we all the same,\r\nour dreams his task,\r\nour hearts his pain,\r\nour sins his fate.\r\n\r\nHow is his house,\r\nwhen is he there,\r\ndoes he ever go out,\r\nis he aware…?\r\n\r\nDoes he understand\r\nthe power of love,\r\nthe meaning of ‘you’\r\nthe reasons of love.\r\n\r\nI’ve never met him,\r\nI’ve just heard what people say\r\nbut I wonder, is he on his own,\r\nlonging for someone,\r\npraying to his god.\r\n\r\n\r\n\r\nHome\r\n\r\nHome,\r\nphysical extension\r\nof my very essence\r\nwhere friends\r\nsit by the fire.\r\n\r\nAnd with\r\nor\r\nwithout\r\nit \r\nunload\r\nthe ephemeral burden\r\nof a hectic\r\nbut absolutely necessary\r\nday\r\nwhich gives \r\nway\r\nto tomorrow. \r\n\r\nHonesty\r\n\r\nDisplaying honesty\r\nalways,\r\nwell,\r\nalmost every time,\r\nfeels\r\nlike jumping\r\nfrom the top\r\nof an incredibly high\r\ncliff\r\nwithout \r\na safety net.\r\n\r\nThe long fall\r\ngives you\r\nenough time\r\nto learn\r\nhow to fly.\r\n\r\nBy taking\r\nside-tracks,\r\nenjoying\r\nthe wrong feeling\r\nat the wrong time,\r\ndistraction\r\ntakes away\r\nthe little time\r\nleft.\r\n\r\nThen,\r\nthe smash\r\nagainst an adverse\r\nreality\r\nis unavoidable.\r\n\r\nIf I ever had to go away\r\n\r\nEvery morning brings a promise\r\nas every tree tells a story.\r\nThousands of streets and only one destination\r\nto walk without touching the ground,\r\nto smile without faking the intention.\r\n\r\nToo many borders and colours and flags\r\nso many feelings that you can’t deny\r\nbut every single time you close your eyes\r\na happy guitar makes the blood in your veins run wild.\r\n\r\nHow could I breathe another air,\r\nwould I smile without the light of the sun above my head\r\nand if I went away, what if I happened to have a doubt\r\nwouldn’t I miss the nervous sea and its confused thoughts.\r\n\r\nCould I also recognise another flower’s scent\r\nand when they talked to me do you think I’d understand\r\nwould a single bottle of wine make us friends after a while.\r\n\r\nWould my memory forget where I come from\r\nyour voice, your smell, your taste and pain.\r\n\r\nIf I have to go away everything under my skin will be my home.\r\nMy eyes will be my stars, my smile my sun\r\nmy feet my vehicle, the memory about you will show me my North\r\nand when the night comes and the cricket sings its song\r\nI’ll be merry because I won’t be alone.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nImagine that you are dreaming\r\n\r\nClose your eyes and look at me\r\ncan you still see me?\r\n\r\nNow put your hands inside your pockets.\r\ncan you still feel me?\r\n\r\nImagine now that you are dreaming\r\nam I still there?\r\n\r\nAnd now open your eyes.\r\nam I gone?\r\n\r\nPretend for a moment that I don’t love you,\r\nwas it easy?\r\n\r\nPretend now that you don’t care about me.\r\nwas it difficult?\r\n\r\nImagine now that you are awake\r\nwhile I’m sleeping by your side.\r\n\r\nIn my dream I haven’t met you yet \r\nbut I’m still looking for you\r\nwhen you, impatient, wake me up…\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nSeeping gravity\r\n\r\nIt’s about time\r\nyou ignored the things you were taught\r\nto do and say.\r\nUnearth the roots of your doubts\r\nand let the plant you are\r\ngrow and cast some shade.\r\n\r\nEverybody seems to know the truth,\r\nthe difference between right and wrong\r\nbut we still fool and fail and fall.\r\n\r\nI’ve wasted too much time\r\npretending to be someone I’m not,\r\nfaking my smile\r\npostponing my goals\r\nbut every time it started to rain\r\neverybody got wet,\r\neverybody got cold.\r\n\r\nTonight the Universe is silent\r\nafraid of disturbing your rest\r\nthe Eagle, first lady of the sky\r\napproaches in silence her nest.\r\n\t\t\t\t\t\t\t\r\nThe waterfalls are dormant,\r\nclaustrophobic waters\r\nstagnated in their own limitation,\r\nsleeping gravity.\r\n\r\nThe book of my thirst is open\r\nblank pages, hermit silence,\r\nlet your dreams, fragile butterflies\r\nrest from their long and tiring journey\r\nand marry the recycled paper,\r\ndiscreet witness\r\nof so many lost battles\r\nand romances\r\nor quests and victories\r\nmaybe promises,\r\nalways realities.\r\n\r\nMy eyes once asked me\r\n‘where’s Beauty gone to?’\r\nI closed them\r\nto concentrate in such \r\na difficult question\r\nwhen I heard them saying\r\n‘oh,\r\nwe see’.\r\n\r\n\r\n\r\n\r\nMasks\r\n\r\nMasks are in\r\nagain\r\none size fits all.\r\n\r\nUpper market ones\r\nare becoming\r\nincreasingly popular.\r\n\r\nFashion victims\r\nwander around\r\nsearching\r\nfor the most ambiguous\r\nones.\r\n\r\nMind you,\r\nthey happen to be\r\nincredibly expensive\r\nand still\r\nyou can always find\r\nsomething seemingly superfluous\r\nto swap them for,\r\nwhat makes them seem\r\naffordable.\r\n\r\nAnd still\r\nI think\r\nI’m too shy\r\nto wear\r\none.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nMingling with gods\r\n\r\nSuddenly there triumphant and complete\r\nthe nights have been long and cold,\r\nthe days never-ending roads,\r\nhundreds of obstacles to overcome.\r\n\r\nYou feel tired and impatient\r\nthe dust blocks your pores, making breathing a difficult task\r\none more challenge for your resolute essence.\r\none more reason for not giving up.\r\n\r\nDid you sacrifice an ephemeral bliss,\r\na temporary haven with a candle as its only sun?\r\nPersistence always has its reward\r\nthe further you get, the lighter the steps.\r\n\r\nHalf man, half angel\r\nyour smile is now your guiding star\r\nas the muscles of your soul start to relax\r\nstop, take a deep breath and enjoy the view of the promised land.\r\n\r\nNature honours you with a standing ovation\r\na waterfall of dreams which purifies your spirit.\r\nYou have conquered a brand new world,\r\nthe power of the waves is now your own reflection.\r\n\r\n\r\nEnjoy this well deserved prize\r\nyou are the only spectator in this unique performance\r\na piece of Heaven on Earth,\r\nthe energy of Life, a perpetual membership in the creation.\r\n\r\nHalf angel, a whole man.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nMorning\r\n\r\nMorning of planes and seagulls\r\nand from the distance\r\nthe whining from the rusty, old, tired factory\r\nof dreams.\r\n\r\nMy eyes \r\nstill to open\r\nnot quite\r\nready for what the excited Sun will bring.\r\n\r\nThe butterfly hasn’t paid me a visit\r\nfor a while.\r\nShe has probably lost her way back home\r\nand is wandering\r\nin circles\r\nlike a winged nomad\r\nin her search\r\nfor the Music\r\nor maybe,\r\nshe doesn’t intend\r\nto ever come back.\r\n\r\nThe crow, my neighbour\r\nscavenges for anything edible\r\nin comforting solitude\r\nstill unaware\r\nof how conscious of your physical extension\r\nan empty stomach\r\ncan make you feel.\r\n\r\nThe heart keeps pumping blood\r\nas that’s its only task\r\nand blood,\r\nstreaming in never-ending rivers of Life\r\nreaches as far as your own existence itself\r\ndrawing an imaginary dividing line\r\nbetween your essence\r\nand the infinite fields\r\nwhere the plants which blossom ‘the questions’ grow.\r\n\r\n\r\nThe butterfly might arrive today\r\nfrom her long and arduous search\r\nfor the land where Music\r\neclipses the artificial value\r\nof words.\r\n\r\nPlanes rarely return from there\r\nas seagulls have been doing\r\nsince time was first measured\r\nbut planes were never taught to share.\r\n\r\nThat’s the very first thing the butterfly learnt form me\r\nand while I look deep into the\r\neyes of the wise horizon\r\nmy heart keeps pumping blood.\r\n\r\nMaybe the rivers of Life\r\nwill someday flow across the fields,\r\nthose fields\r\nwhere the plants which blossom aromatic music\r\ngrow.\r\n\r\nLike the flowers of tomorrow,\r\nlike your dreams of yesterday.\r\n\r\n\r\nMs Understanding\r\n\r\nI’m not sure\r\nhow to take it,\r\nbeing understood \r\nI mean.\r\n\r\nSuch an unfathomable wisdom\r\nserved on a delicate ancient tray;\r\nnever as edible\r\nas simple thoughts.\r\n\r\nYou say\r\nyou know\r\nwhat I \r\nmean.\r\nDo you\r\nreally?\r\n\r\nHow bright is the flame\r\nthat crowns us\r\nas the mighty kings\r\nof an ephemeral darkness.\r\n\r\nWhen switching the light\r\non\r\nthe chemistry seems\r\nto gradually fade\r\naway\r\nuntil our own shadows\r\nare all what is left.\r\n\r\nI know what you mean\r\neven when you are \r\njust thinking \r\naloud\r\nStop thinking!\r\n\r\nI got your point.\r\n\r\n\r\n\r\n\r\nThe infinite field\r\n\r\n\r\nA sudden blow of frosty wind\r\nit comes from nowhere,\r\nor at least\r\nfrom nowhere you’ve been to before.\r\n\r\n\r\nYour limbs are numb\r\nand your blood,\r\nyour blood reposes stagnated,\r\nstagnated like the rivers of Winter.\r\n\r\n\r\nYou suffer and breathe the gelid night\r\nthe winter has arrived\r\nyou feel it in your bones\r\nand you see it\r\nprojected on a  gigantic white screen\r\nthe screen that time magnifies\r\nand your brain erects\r\nso you can see\r\nhow your already lived seconds\r\nlook like.\r\n\r\n\r\nWarmth, the true essence of Life\r\nand Life, \r\nLife seems to be fading away\r\nwalking slowly to the other side\r\nwherever it may be\r\nwhile you urgently need that warmth\r\nand decide, too aware\r\nof the non-existence of an option,\r\nto walk by her side\r\nbeing your own Life’s travelling companion\r\nin a hopeful journey\r\nheading for the land where the Sun,\r\nthe great provider,\r\nlays his nest.\r\n\r\n\r\nAnd maybe up or down there,\r\na sudden blow of warm, comforting wind\r\nwill push open\r\nthe rusty locks which keep\r\nthe heavy doors of your own world shut\r\npresenting you\r\nwith the long awaited view of an infinite field\r\nand now you,\r\nyou are your own limitation.\r\n\r\n\r\n\r\nOne country one faith\r\n\r\nGolden rust covers its legend\r\nwhile brand new dreamers are born every day.\r\nTiny plants struggle to grow\r\nneglected by the purifying rain.\r\n\r\nUp there the golden star is watching\r\nflirting with the Sea, wise goddess on Earth.\r\nRusty bells are tolled in the distance\r\nwhile the tiny snowy church waits resigned for ‘them’.\r\n\r\nBut they are not there anymore\r\nmaybe you can see their flesh but their souls have gone away.\r\nOne night while we were sleeping a thief broke into our veins\r\ntaking away our identity, our words, our essence, our pride.\r\n\r\nSo we took boats, cars and plains\r\nleaving behind our much loved Spain\r\nwith one resolution as our only luggage.\r\nThe determination of finding respect.\r\n\r\nThe morning will come,\r\nthe Sea will relax her tense muscles \r\nand will kiss the Sun on his face.\r\nThe wind will blow gently swallowing the dust\r\nrevealing his secrets to those who listen with open ears.\r\n\r\n\r\nAt last the rain will arrive\r\nand the flowers will smile once more\r\nthen I will look at you while you hold my hand.\r\n\r\nI will whisper at your ear the words we taught\r\nand on a silver tray I will give you my heart,\r\nmy essence, my soul.\r\n\r\nThe Sun and the Sea will witness our love\r\nand we will be grateful for theirs.\r\nSoul and flesh as one again.\r\n\r\nOne only country, only one faith.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nParadise lost, paradise found\r\n\r\n\r\nIt’s too late now!\r\nI used to watch you all\r\nfrom my side of the fence.\r\nthat fence which kept me away from your paradise.\r\n\r\n\r\nI always dreamt of being part of it.\r\nHow beautiful it seemed to me.\r\nI saw you smiling; safe and complete.\r\n\r\n\r\nthere were no fountains with fresh crystal water\r\nbut the sky was always blue\r\nand the sun was always shining\r\nbut I stood at the other side\r\nand out there, there was always a storm.\r\n\r\n\r\nIt was always raining and I felt so cold.\r\nAt some point I stopped dreaming of coming in\r\nbut I still wanted to be part of it.\r\n\r\n\r\nI wasn’t looking for anything else\r\nand you gave me indifference for free.\r\nI never stopped dreaming\r\nand in my dreams I created a tailor-made paradise for myself.\r\n\r\n\r\nIt wasn’t as yours\r\nbut it satisfied my needs.\r\n\r\n\r\nNow the leaves of paradise have yellowed\r\nand the fence is rusty, old and weak.\r\n\r\n\r\nNow you look at me from the other side\r\nso proud to ask, while shivering nervously\r\nso ashamed to pay me a visit.\r\nSo far, when I’d love to share my haven with you.\r\nIf you only asked…\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nPhysical Geography\r\n\r\n\r\nIn a effortless attempt\r\nI climbed the highest mountain\r\nand once up there,\r\nat the peak,\r\nI could remember\r\nwhat I was searching for.\r\n\r\n\r\nI learned the answers\r\nto questions never asked.\r\nYes became maybe\r\nand never was no longer acceptable.\r\n\r\n\r\nI only know about things\r\nI haven’t experienced yet\r\nand however I learn\r\nto forget a little more\r\nevery day.\r\n\r\n\r\nNot making sense\r\nis the best way\r\nof saying it all\r\nand still,\r\nwords\r\ncan sometimes be\r\nan indomitable river\r\nwhich brings together\r\ntwo cities\r\nin the map of love.\r\n\r\n\r\n\r\nRed wine\r\n\r\nLet me drink of your wisdom\r\nso I can finish my book,\r\nlet me burn in Hell\r\nand when I’m about to disintegrate\r\nstop it all\r\nand whisper at my ear\r\n‘It was only a dream, a bad dream’.\r\n\r\nI‘ll let you read\r\nwhat is written in my eyes\r\nand tasting the most delicious wine \r\nbrought to us \r\nfrom the gods’ cellars\r\nI will let you explore\r\nthe intricate paths\r\nwhich lead to my nomad heart.\r\n\r\nI will pretend that you have surprised me\r\nand the pure white moon\r\nwill come down\r\nslowly, furtively\r\nand she will pretend\r\nshe was around in the neighbourhood… \r\n\r\nShe will let  me kiss her\r\nbut only once and once only\r\nand when I am about to disintegrate\r\nstop it all \r\nand whisper to my ear\r\nwhat you know I want to hear.\r\n\r\n\r\n\r\n\r\nRemember to forget\r\n\r\nRemember to forget\r\nthat we were once the present.\r\nDays chased nights\r\nand nights brought your presence.\r\n\r\nLove was the light\r\nand darkness our haven.\r\n\r\nRemember,\r\nbecause memory,\r\nmemory is all we’ve got left,\r\nnothing more\r\nand hardly anything else.\r\n\r\n\r\n\r\nRevolution\r\n\r\nRed snakes and yellow crows\r\ncrystal guitars, shiny faces\r\nmetallic sounds of thunder, one thousand races\r\nthe wind of freedom hits my face.\r\n\r\nWinners and losers\r\nwalking with their leather shoes,\r\ndusty records of screaming blues.\r\n\r\nLove and hate, hearts and souls.\r\nchildren who’ve been growing up for ages\r\nand the wind of freedom hits my face.\r\n\r\nEvolution replaces confusion.\r\nmy memory reflects my frustration.\r\nliving blood runs through the nations,\r\n\r\nmaybe it’s time for Revolution.\r\n\r\n\r\nSecrets\r\n\r\nThe secrets kept within his walled world\r\ngrow like fragile butterflies\r\nafraid of all the bored mouths,\r\nruthless predators\r\nwhich in just a split second\r\ncan turn  a fertile forest\r\ninto a barren lifeless land.\r\n\r\nOnce the butterflies make it\r\ninto the outside world\r\ntransparency becomes a feared alien\r\nsoon bound to be eliminated.\r\n\r\nAn army of poisonous scorpions\r\nchase, siege and eventually inject\r\ntheir lethal venom\r\ninto the inoffensive butterflies\r\ncontaminating their purity, \r\ngranting them\r\nthe most undignified death.\r\n\r\nMind what you say! \r\n\r\n\r\n\r\nSince you have a heart\r\n\r\nSince you have a heart\r\nyou might as well use it.\r\nMake some people happy\r\nand if it happens to break\r\nor be broken\r\nit will heal \r\nand grow stronger.\r\n\r\nIt won’t just pump blood\r\nto your thirsty veins\r\nit will bring happiness\r\nto hungry souls.\r\n\r\nAnd if you ever\r\ntaken for granted,\r\nif you ever give \r\nto the point of getting empty\r\ndon’t feel disappointed.\r\n\r\nYou live because you love\r\nyou’ve got to take some chances.\r\nYou can never love too much\r\nso, if someone thinks you do,\r\nsince you have a brain \r\nyou might as well use it.\r\n\r\nEvery room has a door\r\nthere’s always a way out.\r\nLove needs love\r\nand brings love.\r\nIt comes and it stays\r\nso, practise Love, loving \r\nand you will be loved.\r\n\r\nSince you have a mouth\r\nyou might as well use it.\r\nYou can never love too much\r\nyou can never say too much about love.\r\n\r\nLove is life,\r\nthe more you love,\r\nthe more you live.\r\nYou can never love too much\r\nand if you’ve ever loved someone,\r\nyou will never die completely.\r\n\r\n\r\n\r\n\r\n\r\nStrong\r\n\r\nSelf-respect\r\nthere’s nothing else\r\nI consider my greatest quest.\r\n\r\nI stand on my feet\r\non a chess board\r\nlooking closely to my left\r\nnot quite sure about my first step\r\nas the cold wind pushes me again.\r\n\r\nLook once more,\r\ntidy up\r\nignore the blurry ghosts of the past.\r\n\r\nEmpty roads, a railway track\r\nand a rucksack full of dust\r\ngrab again the slightest pain\r\nwrite some notes \r\nraise your head.\r\n\r\nCount once more from one to ten\r\nfire a look\r\nlet it land \r\ndon’t forget you’re just a man .\r\nCoincidence is better left\r\nto its own devices.\r\n\r\n\r\n\r\nLike the painting you grew to love\r\nits every line, its every dot\r\nno need to try that hard anymore\r\nyou are as strong as you \r\nbelieve you can be\r\nyou can always see\r\nsome birds flying \r\ndodging the storm.\r\n\r\nIt hasn’t been proved\r\nyet \r\nthat you can’t\r\ngrow\r\nyour own\r\nwings.\r\n\r\nMake someone happy\r\ntoday,\r\nopen\r\nyourself\r\nup\r\nopen yourself \r\nup\r\nthe only way\r\nis up.\r\n\r\n\r\nThe compass within\r\n\r\nTrust your instincts\r\nand if \r\nwhile being carried away\r\nyou feel homesick,\r\nunable to find your North.\r\n\r\nMaybe\r\nyou left a window open\r\nand you need to go\r\nback\r\nand shut it\r\nfor ever.\r\n\r\nTrust your instincts\r\nand if you know\r\nI’m not you,\r\nthat’s fine .\r\n\r\nJust say hello.\r\nHowever,\r\nthere might be \r\na diversion \r\nat the end of the road\r\nthough you might not see it\r\nwith your eyes open\r\nand miss \r\nthe way back home.\r\n\r\nThe cotton fields\r\n\r\nI wanted to see more things\r\nenjoy different smiles\r\nwake up in different beds\r\nand let new experiences feed my mind.\r\n\r\nI had seen the birds flying among the clouds\r\nreaching for the sun without looking back to the ground.\r\nI wanted to extend my wings,\r\nascend slowly and once up there enjoy my bliss\r\n\r\nMy crystal dreams shattered in one hundred tiny pieces\r\nthe wind started blowing pushing them towards the sky.\r\nI took a plane carrying a suitcase full of kisses\r\nand said good-bye without faking a smile.\r\n\r\nThe man-made bird broke free\r\nand my heart started beating faster.\r\nMy closed eyes showed me an open field.\r\nThe infinity much closer\r\nLife itself would be my master.\r\n\r\n\r\n\r\n\r\n\r\n\r\nThe dream\r\n\r\nLords of the winds, owners of my will\r\ncould I have your attention for a split second.\r\nI need to know…\r\nI am trying to see but everything seems to be so dark\r\nI hear voices coming from inside my mind\r\nI say words I’ve never heard before.\r\n\r\nA thousand butterflies share my stomach with my guts,\r\ncrazy horses take me to a place I’ve never been before\r\nbut somehow I believe I am at home.\r\n\r\nThere’s nobody with me but I don’t feel alone\r\nI hear music now and I start smiling\r\nThere’s a mirror and I can’t help looking at it.\r\n\r\nI see you there,\r\nyour hand crosses the glass and holds my hand\r\nthen you start singing for me,\r\nmy smile becomes your smile.\r\n\r\nLords of the winds,\r\nyou don’t own my will anymore\r\nplease help me, I need to know\r\nam I dreaming what I am now living\r\nor is it just what they call love.\r\n\r\n\r\nThe epitome of Love\r\n\r\nCross-legged,\r\nbare feet,\r\nclear minded\r\nresting on a soft dune\r\npatiently awaiting a new sunset.\r\n\r\nNot a single cloud in the sky\r\nnot a single doubt in my mind\r\nand then, by spontaneous magic\r\nthe surface of the Earth cracks open\r\ngiving birth to a brand new night.\r\n\r\nMy footsteps in the sand\r\nconcealed by the warm sirocco.,\r\nonce more the stars will show\r\nme the way back home\r\n\r\nhome, you\r\n\r\nyou, home\r\n\r\nI’m tired but resolute\r\nI can trust darkness\r\nI can rely on my steps\r\nthey always take me to you\r\nthere’s only one way to go\r\nand you are my guiding star.\r\n\r\nYou keep my boat from sinking\r\nand listen with open ears,\r\nyou are the fountain from which I keep drinking\r\nand dissolve my silliest fears.\r\n\r\nThere’s no need to run\r\nI’m not alone in my quest\r\nyou are my travelling companion,\r\nmy North, my South, my East and West.\r\n\r\nLike water to a moribund plant\r\na zebra-crossing to a busy road\r\nthe gift of Life,\r\n\r\nthe epitome of Love.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nThe guardian of the stars\r\n\r\nCutting the night\r\nin asymmetric halves\r\nturning laughs into rusty groans\r\n‘the guardian of the stars’\r\nstanding on my shoulders\r\nwaiting\r\nfor better times to come,\r\nopens the book\r\nand from the ‘Holy Scriptures’\r\nretrieves an applicable clause\r\nthat hammers\r\nthe innocence of a peaceful smile.\r\n\r\nLike he who knows\r\nwhat’s written in every book\r\nwithout having ever\r\nturned a single page\r\nbefore.\r\n\r\nLike he who has never\r\nsmelled\r\nthe scent\r\nof the pages \r\nof an old book.\r\n\r\nLike he \r\nwho’s come \r\nform a distant planet.\r\n\r\nHe opens\r\nhis willing\r\nand narcissist mouth\r\nand words, together,\r\ntransform themselves\r\ninto heavy chains\r\nwhich drag you \r\nto the ground.\r\n\r\nAnd you,\r\nlay on the floor\r\ndrowning in a sea of perplexity\r\nunwilling to believe\r\nthat ‘the guardian of the stars’\r\nhas just\r\nswitched them\r\noff.\r\n\r\n\r\n\r\n\r\n\r\nThe lightning guide\r\n\r\nI was running while you were walking,\r\nyou heard me scream while you were talking\r\nbut I didn’t want to take a break to breathe.\r\n\r\nI had walked many streets before the sun of a new day arrived\r\nI fought with the night to make it wait a while\r\nbecause I didn’t want to take a break to breathe.\r\n\r\nI had dreams that made me feel happy \r\nbut I never paid attention to reality\r\nand I didn’t want to take a break to breathe.\r\n\r\nSuddenly you were walking by my side\r\nand your words were a lightning guide\r\nand I didn’t want to take a break to breathe.\r\n\r\nThe sun of a day found me dreaming on my bed\r\nI woke up and the dream was still there\r\nand I didn’t want to take a break to breathe.\r\n\r\nI saw you in this dream; you were holding my hand\r\nI stopped, looked around, smiled\r\nand I took a break to breathe the same air as you.\r\n\r\n\r\n\r\n\r\n\r\n\r\nThe perfect stranger\r\n\r\nA pleasant surprise\r\nlike a white dove\r\nflying low\r\nover a bloody battlefield.\r\n\r\nA sudden smile\r\nlike a waterfall of life\r\nthat refreshes you\r\nfrom a non-definite distance.\r\n\r\nA Bermuda triangle\r\nthat makes\r\nsailing in a sea of curiosity\r\nan exciting adventure.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nWhile you,\r\nthe epicentre of  a circle\r\nof sincere smiles\r\nand crossed words\r\naware of a rare welcoming aura,\r\nglowing and peaceful, \r\nrealise\r\nthat the perfect stranger\r\nhas like you\r\nbeen hypnotised\r\nby the mesmerising song\r\nof the mermaids.\r\n\r\nHis eyes,\r\nfrom a now definite distance\r\nseem to suggest\r\nthat you both team up\r\nand meet them. \r\n\r\n\r\nThe quest\r\n\r\n\r\nThe first time I raised my head\r\nI saw chains of never-ending clouds.\r\nAdverse eyes watched me through dusty windows\r\nand that faint voice inside started to shout loud.\r\n\r\n\r\nThose days are now long gone\r\nthose times of silent thoughts;\r\nmy faith became my bible,\r\nmy self-respect my Soul.\r\n\r\n\r\nI wouldn’t swim at night\r\nthe sea was dark and cold\r\nbut then I raised my head\r\nand the reflection of the moon \r\nencouraged me to find my North.\r\n\r\n\r\nNow I swim, run and jump\r\nI listen, talk and create but don’t expect.\r\nNo present was ever made to me\r\nI am what I’ve got.\r\n\r\n\r\nI grow older making mistakes\r\nyou were one, I am the rest\r\nI am my only gift,\r\nmy most successful quest. \r\n\r\nThe request\r\n\r\nYou have requested me to stop loving you\r\nas if that was possible.\r\n\r\nIf that makes you happy\r\nI’m willing to make an effort.\r\n\r\nI will not talk to you\r\nand you won’t appear in my dreams\r\nanymore.\r\n\r\nBut stop loving you!\r\nI can’t promise you that\r\nit’s not up to me anymore\r\nyou see,\r\nI transferred the case\r\nto the High Tribunal of my heart\r\nand they know much more about love\r\nthan my rationality may suggest.\r\n\r\nI’m sorry\r\nyour request\r\nhas been refused\r\nfor lack of valid arguments.\r\n\r\n\r\nThe secret garden\r\n\r\nOn the generous shade of a weeping willow\r\nI first discovered the infatuation of fire,\r\ngreen leaves caressed by a gentle breeze\r\nas we were dancing around the possessed flames.\r\n\r\nEyes wide open, framed by smiles\r\nand my clothes reeking of smoke\r\nor not quite so.\r\n\r\nTranspiring innocence, walking like numb\r\nfeeling your presence as an extension of mine\r\nyou had been there all along\r\nbut I had needed a tear\r\nto wash away the blindness of my eyes.\r\n\r\nI heard myself saying\r\n‘let me show you,\r\nthis is the miracle of Life,\r\nbut don’t look with your eyes\r\nas they can deceive you\r\nclose them,\r\nlook with  your heart\r\nand you’ll see \r\nwhat words put together fail to describe\r\nwhat brings a smile to a dying land.\r\n\r\n\r\n\r\nThe silence and the voice\r\n(Ode to the telephone)\r\n\r\nCold and hermetic and like Pandora’s box\r\nfull of emptiness, filled with illusion.\r\nSometimes seen as a god.\r\n\r\nI beg him to tell me something.\r\nI want to hear his song;\r\nabsolute deafness.\r\nHe is the master of the Silence,\r\nhe is the owner of the Voice.\r\n\r\nAm I a free slave?\r\nWhen he calls me, there I am.\r\nSubmissive, I forget about my bitterness\r\nand decide that this will be the last time.\r\n\r\nLove and hate, will and fate\r\nand however, accomplice in his crime.\r\n\r\n\r\n\r\nThe wisdom of trees\r\n\r\nI meant to write a poem.\r\nI thought I could talk about you.\r\nI really wanted to let them know how special you are to me\r\nbut my muse is gone.\r\n\r\nMaybe it’s because I haven’t paid much attention to her lately,\r\nbut how could I have.\r\nShould I say that you have become my inspiration.\r\nI mean now I’m starting to see the things I used to write about.\r\n\r\nI’d say I appreciate now the wisdom of trees\r\nand I can guess where those birds are heading to.\r\n\r\nI guess we all are searching for the same thing\r\nthe warmth of someone else’s heart,\r\nkindness, respect and even a little bit of romance.\r\nSomeone to help us to believe that there’s a genuine smile out there.\r\n\r\nBut the papers don’t mention it.\r\nThey never talk about you, they never talk about me\r\nwill they ever mention us\r\nor is it just the thought of a ‘you’\r\nimpartial and unnecessarily essential to me.\r\n\r\nWell, if at least I could write a poem about you\r\nbut then again, \r\nmy muse is gone.\r\n\r\nWe walk on thin ice\r\n\r\nWe walk on tin ice\r\ntrying to cross a never-ending sea of illusions.\r\nThe more we advance the heavier we get.\r\n\r\nI can see the plants we grew \r\nliving ghosts beneath the crystal surface,\r\nlive memories of lost time\r\n\r\nOur inner sun doesn’t acknowledge them anymore\r\nbut somehow they pursue their vital challenge;\r\nto ascend innocently unaware of the stubborn ceiling.\r\n\r\nA jungle of life agonises underneath our feet\r\nwhile our steps start getting deeper on the dying land.\r\n\r\nThe sudden arrival of the sun\r\nprovokes a gentle breeze of hope\r\nas the dividing line\r\nbetween the dizzy present and the present past melts.\r\n\r\nAs we start to fall our love-mad plants avoid the smash.\r\nsuccessfully they reach the surface.\r\nthe sun welcomes them.\r\n\r\nIt’s time to grow more life.\r\n\r\n\r\nWords\r\n\r\nWords\r\nwhich sound like dogs,\r\nfiery tied-up dogs\r\nbarking in the middle of the night\r\nawaking you,\r\nalarming your already\r\nrestless soul\r\nso hungry for a good sleep.\r\n\r\nAnd then silence,\r\nunbearable emptiness,\r\nloud silence\r\nthat awakes \r\nthe now baby-like sleeping dogs\r\nwhile you long,\r\nyou long to hear those words.\r\n\r\nBut those words\r\nand the mouth that awakes them\r\nare fast asleep\r\nexhausted by the arduous task\r\nof bringing together\r\nnight\r\nand day…\r\n\r\nMystical glow\r\n\r\nA colossal shadow\r\non its last metamorphic phase\r\nrests on the façade\r\nof a house\r\nhold.\r\n\r\nSeemingly hostile\r\nas the unknown\r\ntends to look,\r\nas the sometimes unwelcome\r\nnight.\r\n\r\nIt’s eyes still closed\r\nawaiting patiently\r\nsome kind of acknowledgement\r\nfrom the one\r\namong the crowd\r\nthat like a herd of soulless sheep\r\npasses it by\r\nhardly noticing it,\r\nunaware\r\nof its actual\r\nbi-dimensional limitation.\r\n\r\n\r\n\r\nAnd I,\r\nby magical coincidence\r\nlocate its existence\r\nwhich shoots sharp\r\nbut inoffensive arrows\r\nwhich strike\r\nmy most vulnerable asset,\r\nmy innocent\r\nbut always alert\r\nconscience.\r\n\r\nA powerful\r\nand throbbing connection\r\nthat will not subside\r\nfor as long \r\nas curiosity\r\nsails the wildest rivers\r\nof my very existence.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nSunday\r\n\r\nAnother day with a borrowed sun\r\nthe washing-line reveals its secrets.\r\n\r\nPolice cars  trying out brand new alarm-clocks.\r\nTrees cheer them up from the pavement\r\nwatched by lions of stone\r\nbored by the history of time.\r\n\r\nOblivious passers-by,\r\nmen who dress like men\r\ndrinking water from the gutter,\r\nscarecrows look envious at the washing-line.\r\n\r\nThe Sun rises in a fruitless attempt to fly\r\nand I find last night’s bill on the kitchen table.\r\n\r\nPharmacies are always shut\r\nwhen you\r\nneed them\r\nmost.\r\n\r\n\r\n\r\n\r\n\r\n\r\nThink twice\r\n\r\nThe silence between thunders,\r\nthe darkness between lightnings,\r\nthe Sky looks like a balloon \r\ninflated to the limit.\r\n\r\nThe pressure of your actions,\r\na box full of gun powder,\r\nit’d take just one frightened spark\r\nto blow it all away.\r\n\r\nI know you\r\ndon’t’ mean to be\r\nmean\r\nbut words,\r\nwords sometimes hurt.\r\n\r\nEven if they hurt\r\nin silence.\r\n\r\nThink twice\r\nabout what you are\r\ngoing to say\r\nnext.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nBecause\r\n\r\n\r\nWhat made me leave the road\r\nto my already set\r\ndestination.\r\n\r\nWhy did I have to listen\r\nto your words\r\nand find them refreshingly revealing.\r\n\r\nHow can I have found\r\nso much sense\r\nin your creed,\r\nyour hired principles,\r\nyour self-explanatory \r\nspiritual nakedness.\r\n\r\nWhy did you have to play\r\nthat instrument\r\nof remorseless torture.\r\n\r\nYour singular voice,\r\nwhich like the burden\r\nof a heavy rusty carriage\r\npulled by fresh horses\r\ngave me an unsolicited gift\r\nto a more advanced stage\r\nof the road.\r\n\r\nWhy did you show\r\nso much\r\ninterest in my silent shouts.\r\n\r\nYou made me feel\r\nso human,\r\nso hopelessly\r\nhuman."
      ],
      author_name: ["Diego Martinez Montano"],
      seed: ["/books/OL20163536M", "/works/OL13009267W", "/authors/OL5921544A"],
      author_key: ["OL5921544A"],
      title: "Those wonderful moments of transitory unconsciousness",
      publish_date: ["2000"],
      type: "work",
      ebook_count_i: 0,
      publish_place: ["London (UK)"],
      edition_count: 1,
      key: "/works/OL13009267W",
      publisher: ["tne 3124Minerva Press"],
      language: ["eng"],
      last_modified_i: 1353371189,
      cover_edition_key: "OL20163536M",
      first_sentence: [
        "Amistad\r\n\r\nIt’s been a while\r\nsince we smiled\r\ntogether\r\nand you keep learning\r\nwhile I try to forget\r\nbut there’s always\r\nsomething new to talk about\r\nsomething that will make you\r\nremember what I’ve forgotten\r\nand will make me\r\nlearn\r\nwhat you already know.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nAwakening\r\n\r\nIt had been raining for several days\r\nand the musical sound of the rain got me to sleep.\r\nNot long after I woke up and my heart was full of bliss.\r\n\r\nEverything in the room seemed to be new and bright\r\nI looked through the window and the storm had gone\r\nall of a sudden I felt so alive.\r\n\r\nI opened my eyes, the windows, the door\r\nand left for good.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nConspiracy of Silence\r\n\r\nWe give each other the eye\r\nhoping\r\nthat the message \r\nwill get through.\r\n\r\nWe are no good\r\nwith words\r\nand meanwhile\r\nTime covers with dust\r\nthe chance of  a lifetime.\r\n\r\nWe scavenge for signs,\r\nerrand smiles like love-arrows\r\nbut they’ll never manage to hit us.\r\n\r\nIn the meantime\r\nwe long ,hope\r\nand grow in despair.\r\n\r\n\r\nMy heart lets go a desperate cry\r\nand I ,\r\nI am too afraid to listen.\r\n\r\nThe truth hurts,\r\nand hurt,\r\nhurt is the last thing I need\r\nright now.\r\n\r\nEven if it came from you. \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nCupid\r\n\r\nA souvenir, \r\na broken angel\r\nrests naked on your bed.\r\n\r\nHis cracked skin\r\nreminds you\r\nof a smile long gone away.\r\n\r\nFrom his head dives a hair\r\nlike a feather,\r\nlanding softly\r\non his always alert wing.\r\n\r\nJust waiting for a sign,\r\na direction\r\nlike the winds show you the way.\r\n\r\nAnd quietly,\r\nlike a kiss is born\r\na silent good bye is muttered.\r\n\r\nTwo, only two feathers\r\nwill cover now\r\nthe hermetically closed eyes\r\nof the sleeping lover.\r\n\r\n\r\nDays\r\n\r\nSlippery snakes\r\n\t\tof Wisdom.\r\nCatch one,\r\nteach her\r\nto move\r\n\t\tslowly,\r\nto watch around,\r\n\r\ndays,\r\ntamed snakes\r\ncurious and inoffensive,\r\nunaware that nights,\r\nnights,\r\nare unscrupulous\r\neagles,\r\n\r\n\t\teagles\r\n\t\twho find their prey\r\nin slow,\r\ncurious,\r\n\t\tinoffensive\r\nsnakes.\r\n\r\nDreams\r\n\r\nIndiscriminate projections\r\nof has been\r\nnot quite are,\r\nstill to be.\r\n\r\nFairies of time,\r\nfoolish directors\r\nof an orchestra\r\nof whispers,\r\ndialogues,\r\nscreams.\r\n\r\nLost souls,\r\npast visitors of paradise,\r\ntravellers of time.\r\n\r\nThey offer you \r\nenjoyable visions\r\nwhich disturb your inner steadiness.\r\n\r\nYour eyes remain closed\r\nto the self-imposed reality,\r\nwhile the person you’ve been,\r\nnot quite are,\r\nstill to be,\r\nwakes up\r\nasking questions\r\nonly the fairies of time\r\ncan answer…\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nExodus\r\n\r\n\r\nHow long does it take\r\none man\r\nto grow up\r\nand above\r\nthe child inside.\r\n\r\n\r\nAt coffee-takes\r\nthe serene mind\r\nwill elaborate\r\ntrying to find\r\nthe right \r\nway out.\r\n\r\n\r\nThe misty lagoon,\r\na labyrinth of heavy water\r\nits thickness blinds,\r\nnowhere to go\r\nnothing much behind\r\nwhile from the other side\r\nthe faint sound of metallic chimes\r\nproposes a new start.\r\n\r\n\r\nGet out there\r\nnever come back\r\ndon’t try to try\r\ndon’t listen much.\r\n\r\n\t\t\t\t\t\t\t\t\r\nI don’t know\r\nwhere to go \r\nDestiny is written with blurry words\r\nI can’t make out\r\nwhere that voice is coming from.\r\njust let me get out\r\nof this claustrophobic sea    \r\nlet me swim with style\r\nsee me going far \r\naway\r\nfrom here.\r\n\r\n\r\nThere’s a man I used to know\r\nI learned so much from him\r\njust like watching a car\r\ndriving so fucking fast.\r\n\r\n\r\n\r\n\r\n\r\nOn the number plate \r\nI could barely read\r\n“See you later on\r\nwhen the rain comes”\r\n\r\nMaybe \r\nsince then\r\nI’ve been longing to get wet\r\nto cross the tunnel\r\nfollow the seagulls\r\nthat promise me land.\r\n\r\n\r\nA firm surface,\r\nthe Sun above my head\r\nagain\r\nI need to close my eyes\r\njust for a minute.\r\n\r\n\r\nI want to see no more\r\nI just want to listen\r\nwith my heart\r\nand hear \r\nthe mermaids singing me \r\nto sleep\r\nuntil I wake up\r\non a bed of secrets.\r\n\r\n\r\nLike the ones kept within your walls;\r\ninnocent flowers\r\nneglected by the lazy gardener\r\nwho once or twice\r\nthought it would be \r\na good idea \r\nto bring some colour \r\nto his uneventful\r\nexistence.    \r\n   \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nFriends\r\n\r\nWhenever it’s cold outside\r\nand I feel like a groom with no bride,\r\n\r\nwhen words are like a jigsaw\r\nand you say the missing ones,\r\n\r\nwhenever I need a shot of altruistic wisdom\r\nor a piece of holy bread,\r\n\r\nwhen the sound of silence\r\nspells out the word friend,\r\n\r\nyou are what I see\r\nyou are what I get\r\n\r\nbrother at thick and thin\r\nyou give the word friend a good name.\r\n\r\n\r\nGod\r\n\r\nWhat does god think,\r\nwhat does god say,\r\nin lonely moments,\r\nto whom does he pray.\r\n\r\nWhat does he see\r\nwhen he opens his eyes\r\nand looks down here.\r\n\r\nAre we all the same,\r\nour dreams his task,\r\nour hearts his pain,\r\nour sins his fate.\r\n\r\nHow is his house,\r\nwhen is he there,\r\ndoes he ever go out,\r\nis he aware…?\r\n\r\nDoes he understand\r\nthe power of love,\r\nthe meaning of ‘you’\r\nthe reasons of love.\r\n\r\nI’ve never met him,\r\nI’ve just heard what people say\r\nbut I wonder, is he on his own,\r\nlonging for someone,\r\npraying to his god.\r\n\r\n\r\n\r\nHome\r\n\r\nHome,\r\nphysical extension\r\nof my very essence\r\nwhere friends\r\nsit by the fire.\r\n\r\nAnd with\r\nor\r\nwithout\r\nit \r\nunload\r\nthe ephemeral burden\r\nof a hectic\r\nbut absolutely necessary\r\nday\r\nwhich gives \r\nway\r\nto tomorrow. \r\n\r\nHonesty\r\n\r\nDisplaying honesty\r\nalways,\r\nwell,\r\nalmost every time,\r\nfeels\r\nlike jumping\r\nfrom the top\r\nof an incredibly high\r\ncliff\r\nwithout \r\na safety net.\r\n\r\nThe long fall\r\ngives you\r\nenough time\r\nto learn\r\nhow to fly.\r\n\r\nBy taking\r\nside-tracks,\r\nenjoying\r\nthe wrong feeling\r\nat the wrong time,\r\ndistraction\r\ntakes away\r\nthe little time\r\nleft.\r\n\r\nThen,\r\nthe smash\r\nagainst an adverse\r\nreality\r\nis unavoidable.\r\n\r\nIf I ever had to go away\r\n\r\nEvery morning brings a promise\r\nas every tree tells a story.\r\nThousands of streets and only one destination\r\nto walk without touching the ground,\r\nto smile without faking the intention.\r\n\r\nToo many borders and colours and flags\r\nso many feelings that you can’t deny\r\nbut every single time you close your eyes\r\na happy guitar makes the blood in your veins run wild.\r\n\r\nHow could I breathe another air,\r\nwould I smile without the light of the sun above my head\r\nand if I went away, what if I happened to have a doubt\r\nwouldn’t I miss the nervous sea and its confused thoughts.\r\n\r\nCould I also recognise another flower’s scent\r\nand when they talked to me do you think I’d understand\r\nwould a single bottle of wine make us friends after a while.\r\n\r\nWould my memory forget where I come from\r\nyour voice, your smell, your taste and pain.\r\n\r\nIf I have to go away everything under my skin will be my home.\r\nMy eyes will be my stars, my smile my sun\r\nmy feet my vehicle, the memory about you will show me my North\r\nand when the night comes and the cricket sings its song\r\nI’ll be merry because I won’t be alone.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nImagine that you are dreaming\r\n\r\nClose your eyes and look at me\r\ncan you still see me?\r\n\r\nNow put your hands inside your pockets.\r\ncan you still feel me?\r\n\r\nImagine now that you are dreaming\r\nam I still there?\r\n\r\nAnd now open your eyes.\r\nam I gone?\r\n\r\nPretend for a moment that I don’t love you,\r\nwas it easy?\r\n\r\nPretend now that you don’t care about me.\r\nwas it difficult?\r\n\r\nImagine now that you are awake\r\nwhile I’m sleeping by your side.\r\n\r\nIn my dream I haven’t met you yet \r\nbut I’m still looking for you\r\nwhen you, impatient, wake me up…\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nSeeping gravity\r\n\r\nIt’s about time\r\nyou ignored the things you were taught\r\nto do and say.\r\nUnearth the roots of your doubts\r\nand let the plant you are\r\ngrow and cast some shade.\r\n\r\nEverybody seems to know the truth,\r\nthe difference between right and wrong\r\nbut we still fool and fail and fall.\r\n\r\nI’ve wasted too much time\r\npretending to be someone I’m not,\r\nfaking my smile\r\npostponing my goals\r\nbut every time it started to rain\r\neverybody got wet,\r\neverybody got cold.\r\n\r\nTonight the Universe is silent\r\nafraid of disturbing your rest\r\nthe Eagle, first lady of the sky\r\napproaches in silence her nest.\r\n\t\t\t\t\t\t\t\r\nThe waterfalls are dormant,\r\nclaustrophobic waters\r\nstagnated in their own limitation,\r\nsleeping gravity.\r\n\r\nThe book of my thirst is open\r\nblank pages, hermit silence,\r\nlet your dreams, fragile butterflies\r\nrest from their long and tiring journey\r\nand marry the recycled paper,\r\ndiscreet witness\r\nof so many lost battles\r\nand romances\r\nor quests and victories\r\nmaybe promises,\r\nalways realities.\r\n\r\nMy eyes once asked me\r\n‘where’s Beauty gone to?’\r\nI closed them\r\nto concentrate in such \r\na difficult question\r\nwhen I heard them saying\r\n‘oh,\r\nwe see’.\r\n\r\n\r\n\r\n\r\nMasks\r\n\r\nMasks are in\r\nagain\r\none size fits all.\r\n\r\nUpper market ones\r\nare becoming\r\nincreasingly popular.\r\n\r\nFashion victims\r\nwander around\r\nsearching\r\nfor the most ambiguous\r\nones.\r\n\r\nMind you,\r\nthey happen to be\r\nincredibly expensive\r\nand still\r\nyou can always find\r\nsomething seemingly superfluous\r\nto swap them for,\r\nwhat makes them seem\r\naffordable.\r\n\r\nAnd still\r\nI think\r\nI’m too shy\r\nto wear\r\none.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nMingling with gods\r\n\r\nSuddenly there triumphant and complete\r\nthe nights have been long and cold,\r\nthe days never-ending roads,\r\nhundreds of obstacles to overcome.\r\n\r\nYou feel tired and impatient\r\nthe dust blocks your pores, making breathing a difficult task\r\none more challenge for your resolute essence.\r\none more reason for not giving up.\r\n\r\nDid you sacrifice an ephemeral bliss,\r\na temporary haven with a candle as its only sun?\r\nPersistence always has its reward\r\nthe further you get, the lighter the steps.\r\n\r\nHalf man, half angel\r\nyour smile is now your guiding star\r\nas the muscles of your soul start to relax\r\nstop, take a deep breath and enjoy the view of the promised land.\r\n\r\nNature honours you with a standing ovation\r\na waterfall of dreams which purifies your spirit.\r\nYou have conquered a brand new world,\r\nthe power of the waves is now your own reflection.\r\n\r\n\r\nEnjoy this well deserved prize\r\nyou are the only spectator in this unique performance\r\na piece of Heaven on Earth,\r\nthe energy of Life, a perpetual membership in the creation.\r\n\r\nHalf angel, a whole man.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nMorning\r\n\r\nMorning of planes and seagulls\r\nand from the distance\r\nthe whining from the rusty, old, tired factory\r\nof dreams.\r\n\r\nMy eyes \r\nstill to open\r\nnot quite\r\nready for what the excited Sun will bring.\r\n\r\nThe butterfly hasn’t paid me a visit\r\nfor a while.\r\nShe has probably lost her way back home\r\nand is wandering\r\nin circles\r\nlike a winged nomad\r\nin her search\r\nfor the Music\r\nor maybe,\r\nshe doesn’t intend\r\nto ever come back.\r\n\r\nThe crow, my neighbour\r\nscavenges for anything edible\r\nin comforting solitude\r\nstill unaware\r\nof how conscious of your physical extension\r\nan empty stomach\r\ncan make you feel.\r\n\r\nThe heart keeps pumping blood\r\nas that’s its only task\r\nand blood,\r\nstreaming in never-ending rivers of Life\r\nreaches as far as your own existence itself\r\ndrawing an imaginary dividing line\r\nbetween your essence\r\nand the infinite fields\r\nwhere the plants which blossom ‘the questions’ grow.\r\n\r\n\r\nThe butterfly might arrive today\r\nfrom her long and arduous search\r\nfor the land where Music\r\neclipses the artificial value\r\nof words.\r\n\r\nPlanes rarely return from there\r\nas seagulls have been doing\r\nsince time was first measured\r\nbut planes were never taught to share.\r\n\r\nThat’s the very first thing the butterfly learnt form me\r\nand while I look deep into the\r\neyes of the wise horizon\r\nmy heart keeps pumping blood.\r\n\r\nMaybe the rivers of Life\r\nwill someday flow across the fields,\r\nthose fields\r\nwhere the plants which blossom aromatic music\r\ngrow.\r\n\r\nLike the flowers of tomorrow,\r\nlike your dreams of yesterday.\r\n\r\n\r\nMs Understanding\r\n\r\nI’m not sure\r\nhow to take it,\r\nbeing understood \r\nI mean.\r\n\r\nSuch an unfathomable wisdom\r\nserved on a delicate ancient tray;\r\nnever as edible\r\nas simple thoughts.\r\n\r\nYou say\r\nyou know\r\nwhat I \r\nmean.\r\nDo you\r\nreally?\r\n\r\nHow bright is the flame\r\nthat crowns us\r\nas the mighty kings\r\nof an ephemeral darkness.\r\n\r\nWhen switching the light\r\non\r\nthe chemistry seems\r\nto gradually fade\r\naway\r\nuntil our own shadows\r\nare all what is left.\r\n\r\nI know what you mean\r\neven when you are \r\njust thinking \r\naloud\r\nStop thinking!\r\n\r\nI got your point.\r\n\r\n\r\n\r\n\r\nThe infinite field\r\n\r\n\r\nA sudden blow of frosty wind\r\nit comes from nowhere,\r\nor at least\r\nfrom nowhere you’ve been to before.\r\n\r\n\r\nYour limbs are numb\r\nand your blood,\r\nyour blood reposes stagnated,\r\nstagnated like the rivers of Winter.\r\n\r\n\r\nYou suffer and breathe the gelid night\r\nthe winter has arrived\r\nyou feel it in your bones\r\nand you see it\r\nprojected on a  gigantic white screen\r\nthe screen that time magnifies\r\nand your brain erects\r\nso you can see\r\nhow your already lived seconds\r\nlook like.\r\n\r\n\r\nWarmth, the true essence of Life\r\nand Life, \r\nLife seems to be fading away\r\nwalking slowly to the other side\r\nwherever it may be\r\nwhile you urgently need that warmth\r\nand decide, too aware\r\nof the non-existence of an option,\r\nto walk by her side\r\nbeing your own Life’s travelling companion\r\nin a hopeful journey\r\nheading for the land where the Sun,\r\nthe great provider,\r\nlays his nest.\r\n\r\n\r\nAnd maybe up or down there,\r\na sudden blow of warm, comforting wind\r\nwill push open\r\nthe rusty locks which keep\r\nthe heavy doors of your own world shut\r\npresenting you\r\nwith the long awaited view of an infinite field\r\nand now you,\r\nyou are your own limitation.\r\n\r\n\r\n\r\nOne country one faith\r\n\r\nGolden rust covers its legend\r\nwhile brand new dreamers are born every day.\r\nTiny plants struggle to grow\r\nneglected by the purifying rain.\r\n\r\nUp there the golden star is watching\r\nflirting with the Sea, wise goddess on Earth.\r\nRusty bells are tolled in the distance\r\nwhile the tiny snowy church waits resigned for ‘them’.\r\n\r\nBut they are not there anymore\r\nmaybe you can see their flesh but their souls have gone away.\r\nOne night while we were sleeping a thief broke into our veins\r\ntaking away our identity, our words, our essence, our pride.\r\n\r\nSo we took boats, cars and plains\r\nleaving behind our much loved Spain\r\nwith one resolution as our only luggage.\r\nThe determination of finding respect.\r\n\r\nThe morning will come,\r\nthe Sea will relax her tense muscles \r\nand will kiss the Sun on his face.\r\nThe wind will blow gently swallowing the dust\r\nrevealing his secrets to those who listen with open ears.\r\n\r\n\r\nAt last the rain will arrive\r\nand the flowers will smile once more\r\nthen I will look at you while you hold my hand.\r\n\r\nI will whisper at your ear the words we taught\r\nand on a silver tray I will give you my heart,\r\nmy essence, my soul.\r\n\r\nThe Sun and the Sea will witness our love\r\nand we will be grateful for theirs.\r\nSoul and flesh as one again.\r\n\r\nOne only country, only one faith.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nParadise lost, paradise found\r\n\r\n\r\nIt’s too late now!\r\nI used to watch you all\r\nfrom my side of the fence.\r\nthat fence which kept me away from your paradise.\r\n\r\n\r\nI always dreamt of being part of it.\r\nHow beautiful it seemed to me.\r\nI saw you smiling; safe and complete.\r\n\r\n\r\nthere were no fountains with fresh crystal water\r\nbut the sky was always blue\r\nand the sun was always shining\r\nbut I stood at the other side\r\nand out there, there was always a storm.\r\n\r\n\r\nIt was always raining and I felt so cold.\r\nAt some point I stopped dreaming of coming in\r\nbut I still wanted to be part of it.\r\n\r\n\r\nI wasn’t looking for anything else\r\nand you gave me indifference for free.\r\nI never stopped dreaming\r\nand in my dreams I created a tailor-made paradise for myself.\r\n\r\n\r\nIt wasn’t as yours\r\nbut it satisfied my needs.\r\n\r\n\r\nNow the leaves of paradise have yellowed\r\nand the fence is rusty, old and weak.\r\n\r\n\r\nNow you look at me from the other side\r\nso proud to ask, while shivering nervously\r\nso ashamed to pay me a visit.\r\nSo far, when I’d love to share my haven with you.\r\nIf you only asked…\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nPhysical Geography\r\n\r\n\r\nIn a effortless attempt\r\nI climbed the highest mountain\r\nand once up there,\r\nat the peak,\r\nI could remember\r\nwhat I was searching for.\r\n\r\n\r\nI learned the answers\r\nto questions never asked.\r\nYes became maybe\r\nand never was no longer acceptable.\r\n\r\n\r\nI only know about things\r\nI haven’t experienced yet\r\nand however I learn\r\nto forget a little more\r\nevery day.\r\n\r\n\r\nNot making sense\r\nis the best way\r\nof saying it all\r\nand still,\r\nwords\r\ncan sometimes be\r\nan indomitable river\r\nwhich brings together\r\ntwo cities\r\nin the map of love.\r\n\r\n\r\n\r\nRed wine\r\n\r\nLet me drink of your wisdom\r\nso I can finish my book,\r\nlet me burn in Hell\r\nand when I’m about to disintegrate\r\nstop it all\r\nand whisper at my ear\r\n‘It was only a dream, a bad dream’.\r\n\r\nI‘ll let you read\r\nwhat is written in my eyes\r\nand tasting the most delicious wine \r\nbrought to us \r\nfrom the gods’ cellars\r\nI will let you explore\r\nthe intricate paths\r\nwhich lead to my nomad heart.\r\n\r\nI will pretend that you have surprised me\r\nand the pure white moon\r\nwill come down\r\nslowly, furtively\r\nand she will pretend\r\nshe was around in the neighbourhood… \r\n\r\nShe will let  me kiss her\r\nbut only once and once only\r\nand when I am about to disintegrate\r\nstop it all \r\nand whisper to my ear\r\nwhat you know I want to hear.\r\n\r\n\r\n\r\n\r\nRemember to forget\r\n\r\nRemember to forget\r\nthat we were once the present.\r\nDays chased nights\r\nand nights brought your presence.\r\n\r\nLove was the light\r\nand darkness our haven.\r\n\r\nRemember,\r\nbecause memory,\r\nmemory is all we’ve got left,\r\nnothing more\r\nand hardly anything else.\r\n\r\n\r\n\r\nRevolution\r\n\r\nRed snakes and yellow crows\r\ncrystal guitars, shiny faces\r\nmetallic sounds of thunder, one thousand races\r\nthe wind of freedom hits my face.\r\n\r\nWinners and losers\r\nwalking with their leather shoes,\r\ndusty records of screaming blues.\r\n\r\nLove and hate, hearts and souls.\r\nchildren who’ve been growing up for ages\r\nand the wind of freedom hits my face.\r\n\r\nEvolution replaces confusion.\r\nmy memory reflects my frustration.\r\nliving blood runs through the nations,\r\n\r\nmaybe it’s time for Revolution.\r\n\r\n\r\nSecrets\r\n\r\nThe secrets kept within his walled world\r\ngrow like fragile butterflies\r\nafraid of all the bored mouths,\r\nruthless predators\r\nwhich in just a split second\r\ncan turn  a fertile forest\r\ninto a barren lifeless land.\r\n\r\nOnce the butterflies make it\r\ninto the outside world\r\ntransparency becomes a feared alien\r\nsoon bound to be eliminated.\r\n\r\nAn army of poisonous scorpions\r\nchase, siege and eventually inject\r\ntheir lethal venom\r\ninto the inoffensive butterflies\r\ncontaminating their purity, \r\ngranting them\r\nthe most undignified death.\r\n\r\nMind what you say! \r\n\r\n\r\n\r\nSince you have a heart\r\n\r\nSince you have a heart\r\nyou might as well use it.\r\nMake some people happy\r\nand if it happens to break\r\nor be broken\r\nit will heal \r\nand grow stronger.\r\n\r\nIt won’t just pump blood\r\nto your thirsty veins\r\nit will bring happiness\r\nto hungry souls.\r\n\r\nAnd if you ever\r\ntaken for granted,\r\nif you ever give \r\nto the point of getting empty\r\ndon’t feel disappointed.\r\n\r\nYou live because you love\r\nyou’ve got to take some chances.\r\nYou can never love too much\r\nso, if someone thinks you do,\r\nsince you have a brain \r\nyou might as well use it.\r\n\r\nEvery room has a door\r\nthere’s always a way out.\r\nLove needs love\r\nand brings love.\r\nIt comes and it stays\r\nso, practise Love, loving \r\nand you will be loved.\r\n\r\nSince you have a mouth\r\nyou might as well use it.\r\nYou can never love too much\r\nyou can never say too much about love.\r\n\r\nLove is life,\r\nthe more you love,\r\nthe more you live.\r\nYou can never love too much\r\nand if you’ve ever loved someone,\r\nyou will never die completely.\r\n\r\n\r\n\r\n\r\n\r\nStrong\r\n\r\nSelf-respect\r\nthere’s nothing else\r\nI consider my greatest quest.\r\n\r\nI stand on my feet\r\non a chess board\r\nlooking closely to my left\r\nnot quite sure about my first step\r\nas the cold wind pushes me again.\r\n\r\nLook once more,\r\ntidy up\r\nignore the blurry ghosts of the past.\r\n\r\nEmpty roads, a railway track\r\nand a rucksack full of dust\r\ngrab again the slightest pain\r\nwrite some notes \r\nraise your head.\r\n\r\nCount once more from one to ten\r\nfire a look\r\nlet it land \r\ndon’t forget you’re just a man .\r\nCoincidence is better left\r\nto its own devices.\r\n\r\n\r\n\r\nLike the painting you grew to love\r\nits every line, its every dot\r\nno need to try that hard anymore\r\nyou are as strong as you \r\nbelieve you can be\r\nyou can always see\r\nsome birds flying \r\ndodging the storm.\r\n\r\nIt hasn’t been proved\r\nyet \r\nthat you can’t\r\ngrow\r\nyour own\r\nwings.\r\n\r\nMake someone happy\r\ntoday,\r\nopen\r\nyourself\r\nup\r\nopen yourself \r\nup\r\nthe only way\r\nis up.\r\n\r\n\r\nThe compass within\r\n\r\nTrust your instincts\r\nand if \r\nwhile being carried away\r\nyou feel homesick,\r\nunable to find your North.\r\n\r\nMaybe\r\nyou left a window open\r\nand you need to go\r\nback\r\nand shut it\r\nfor ever.\r\n\r\nTrust your instincts\r\nand if you know\r\nI’m not you,\r\nthat’s fine .\r\n\r\nJust say hello.\r\nHowever,\r\nthere might be \r\na diversion \r\nat the end of the road\r\nthough you might not see it\r\nwith your eyes open\r\nand miss \r\nthe way back home.\r\n\r\nThe cotton fields\r\n\r\nI wanted to see more things\r\nenjoy different smiles\r\nwake up in different beds\r\nand let new experiences feed my mind.\r\n\r\nI had seen the birds flying among the clouds\r\nreaching for the sun without looking back to the ground.\r\nI wanted to extend my wings,\r\nascend slowly and once up there enjoy my bliss\r\n\r\nMy crystal dreams shattered in one hundred tiny pieces\r\nthe wind started blowing pushing them towards the sky.\r\nI took a plane carrying a suitcase full of kisses\r\nand said good-bye without faking a smile.\r\n\r\nThe man-made bird broke free\r\nand my heart started beating faster.\r\nMy closed eyes showed me an open field.\r\nThe infinity much closer\r\nLife itself would be my master.\r\n\r\n\r\n\r\n\r\n\r\n\r\nThe dream\r\n\r\nLords of the winds, owners of my will\r\ncould I have your attention for a split second.\r\nI need to know…\r\nI am trying to see but everything seems to be so dark\r\nI hear voices coming from inside my mind\r\nI say words I’ve never heard before.\r\n\r\nA thousand butterflies share my stomach with my guts,\r\ncrazy horses take me to a place I’ve never been before\r\nbut somehow I believe I am at home.\r\n\r\nThere’s nobody with me but I don’t feel alone\r\nI hear music now and I start smiling\r\nThere’s a mirror and I can’t help looking at it.\r\n\r\nI see you there,\r\nyour hand crosses the glass and holds my hand\r\nthen you start singing for me,\r\nmy smile becomes your smile.\r\n\r\nLords of the winds,\r\nyou don’t own my will anymore\r\nplease help me, I need to know\r\nam I dreaming what I am now living\r\nor is it just what they call love.\r\n\r\n\r\nThe epitome of Love\r\n\r\nCross-legged,\r\nbare feet,\r\nclear minded\r\nresting on a soft dune\r\npatiently awaiting a new sunset.\r\n\r\nNot a single cloud in the sky\r\nnot a single doubt in my mind\r\nand then, by spontaneous magic\r\nthe surface of the Earth cracks open\r\ngiving birth to a brand new night.\r\n\r\nMy footsteps in the sand\r\nconcealed by the warm sirocco.,\r\nonce more the stars will show\r\nme the way back home\r\n\r\nhome, you\r\n\r\nyou, home\r\n\r\nI’m tired but resolute\r\nI can trust darkness\r\nI can rely on my steps\r\nthey always take me to you\r\nthere’s only one way to go\r\nand you are my guiding star.\r\n\r\nYou keep my boat from sinking\r\nand listen with open ears,\r\nyou are the fountain from which I keep drinking\r\nand dissolve my silliest fears.\r\n\r\nThere’s no need to run\r\nI’m not alone in my quest\r\nyou are my travelling companion,\r\nmy North, my South, my East and West.\r\n\r\nLike water to a moribund plant\r\na zebra-crossing to a busy road\r\nthe gift of Life,\r\n\r\nthe epitome of Love.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nThe guardian of the stars\r\n\r\nCutting the night\r\nin asymmetric halves\r\nturning laughs into rusty groans\r\n‘the guardian of the stars’\r\nstanding on my shoulders\r\nwaiting\r\nfor better times to come,\r\nopens the book\r\nand from the ‘Holy Scriptures’\r\nretrieves an applicable clause\r\nthat hammers\r\nthe innocence of a peaceful smile.\r\n\r\nLike he who knows\r\nwhat’s written in every book\r\nwithout having ever\r\nturned a single page\r\nbefore.\r\n\r\nLike he who has never\r\nsmelled\r\nthe scent\r\nof the pages \r\nof an old book.\r\n\r\nLike he \r\nwho’s come \r\nform a distant planet.\r\n\r\nHe opens\r\nhis willing\r\nand narcissist mouth\r\nand words, together,\r\ntransform themselves\r\ninto heavy chains\r\nwhich drag you \r\nto the ground.\r\n\r\nAnd you,\r\nlay on the floor\r\ndrowning in a sea of perplexity\r\nunwilling to believe\r\nthat ‘the guardian of the stars’\r\nhas just\r\nswitched them\r\noff.\r\n\r\n\r\n\r\n\r\n\r\nThe lightning guide\r\n\r\nI was running while you were walking,\r\nyou heard me scream while you were talking\r\nbut I didn’t want to take a break to breathe.\r\n\r\nI had walked many streets before the sun of a new day arrived\r\nI fought with the night to make it wait a while\r\nbecause I didn’t want to take a break to breathe.\r\n\r\nI had dreams that made me feel happy \r\nbut I never paid attention to reality\r\nand I didn’t want to take a break to breathe.\r\n\r\nSuddenly you were walking by my side\r\nand your words were a lightning guide\r\nand I didn’t want to take a break to breathe.\r\n\r\nThe sun of a day found me dreaming on my bed\r\nI woke up and the dream was still there\r\nand I didn’t want to take a break to breathe.\r\n\r\nI saw you in this dream; you were holding my hand\r\nI stopped, looked around, smiled\r\nand I took a break to breathe the same air as you.\r\n\r\n\r\n\r\n\r\n\r\n\r\nThe perfect stranger\r\n\r\nA pleasant surprise\r\nlike a white dove\r\nflying low\r\nover a bloody battlefield.\r\n\r\nA sudden smile\r\nlike a waterfall of life\r\nthat refreshes you\r\nfrom a non-definite distance.\r\n\r\nA Bermuda triangle\r\nthat makes\r\nsailing in a sea of curiosity\r\nan exciting adventure.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nWhile you,\r\nthe epicentre of  a circle\r\nof sincere smiles\r\nand crossed words\r\naware of a rare welcoming aura,\r\nglowing and peaceful, \r\nrealise\r\nthat the perfect stranger\r\nhas like you\r\nbeen hypnotised\r\nby the mesmerising song\r\nof the mermaids.\r\n\r\nHis eyes,\r\nfrom a now definite distance\r\nseem to suggest\r\nthat you both team up\r\nand meet them. \r\n\r\n\r\nThe quest\r\n\r\n\r\nThe first time I raised my head\r\nI saw chains of never-ending clouds.\r\nAdverse eyes watched me through dusty windows\r\nand that faint voice inside started to shout loud.\r\n\r\n\r\nThose days are now long gone\r\nthose times of silent thoughts;\r\nmy faith became my bible,\r\nmy self-respect my Soul.\r\n\r\n\r\nI wouldn’t swim at night\r\nthe sea was dark and cold\r\nbut then I raised my head\r\nand the reflection of the moon \r\nencouraged me to find my North.\r\n\r\n\r\nNow I swim, run and jump\r\nI listen, talk and create but don’t expect.\r\nNo present was ever made to me\r\nI am what I’ve got.\r\n\r\n\r\nI grow older making mistakes\r\nyou were one, I am the rest\r\nI am my only gift,\r\nmy most successful quest. \r\n\r\nThe request\r\n\r\nYou have requested me to stop loving you\r\nas if that was possible.\r\n\r\nIf that makes you happy\r\nI’m willing to make an effort.\r\n\r\nI will not talk to you\r\nand you won’t appear in my dreams\r\nanymore.\r\n\r\nBut stop loving you!\r\nI can’t promise you that\r\nit’s not up to me anymore\r\nyou see,\r\nI transferred the case\r\nto the High Tribunal of my heart\r\nand they know much more about love\r\nthan my rationality may suggest.\r\n\r\nI’m sorry\r\nyour request\r\nhas been refused\r\nfor lack of valid arguments.\r\n\r\n\r\nThe secret garden\r\n\r\nOn the generous shade of a weeping willow\r\nI first discovered the infatuation of fire,\r\ngreen leaves caressed by a gentle breeze\r\nas we were dancing around the possessed flames.\r\n\r\nEyes wide open, framed by smiles\r\nand my clothes reeking of smoke\r\nor not quite so.\r\n\r\nTranspiring innocence, walking like numb\r\nfeeling your presence as an extension of mine\r\nyou had been there all along\r\nbut I had needed a tear\r\nto wash away the blindness of my eyes.\r\n\r\nI heard myself saying\r\n‘let me show you,\r\nthis is the miracle of Life,\r\nbut don’t look with your eyes\r\nas they can deceive you\r\nclose them,\r\nlook with  your heart\r\nand you’ll see \r\nwhat words put together fail to describe\r\nwhat brings a smile to a dying land.\r\n\r\n\r\n\r\nThe silence and the voice\r\n(Ode to the telephone)\r\n\r\nCold and hermetic and like Pandora’s box\r\nfull of emptiness, filled with illusion.\r\nSometimes seen as a god.\r\n\r\nI beg him to tell me something.\r\nI want to hear his song;\r\nabsolute deafness.\r\nHe is the master of the Silence,\r\nhe is the owner of the Voice.\r\n\r\nAm I a free slave?\r\nWhen he calls me, there I am.\r\nSubmissive, I forget about my bitterness\r\nand decide that this will be the last time.\r\n\r\nLove and hate, will and fate\r\nand however, accomplice in his crime.\r\n\r\n\r\n\r\nThe wisdom of trees\r\n\r\nI meant to write a poem.\r\nI thought I could talk about you.\r\nI really wanted to let them know how special you are to me\r\nbut my muse is gone.\r\n\r\nMaybe it’s because I haven’t paid much attention to her lately,\r\nbut how could I have.\r\nShould I say that you have become my inspiration.\r\nI mean now I’m starting to see the things I used to write about.\r\n\r\nI’d say I appreciate now the wisdom of trees\r\nand I can guess where those birds are heading to.\r\n\r\nI guess we all are searching for the same thing\r\nthe warmth of someone else’s heart,\r\nkindness, respect and even a little bit of romance.\r\nSomeone to help us to believe that there’s a genuine smile out there.\r\n\r\nBut the papers don’t mention it.\r\nThey never talk about you, they never talk about me\r\nwill they ever mention us\r\nor is it just the thought of a ‘you’\r\nimpartial and unnecessarily essential to me.\r\n\r\nWell, if at least I could write a poem about you\r\nbut then again, \r\nmy muse is gone.\r\n\r\nWe walk on thin ice\r\n\r\nWe walk on tin ice\r\ntrying to cross a never-ending sea of illusions.\r\nThe more we advance the heavier we get.\r\n\r\nI can see the plants we grew \r\nliving ghosts beneath the crystal surface,\r\nlive memories of lost time\r\n\r\nOur inner sun doesn’t acknowledge them anymore\r\nbut somehow they pursue their vital challenge;\r\nto ascend innocently unaware of the stubborn ceiling.\r\n\r\nA jungle of life agonises underneath our feet\r\nwhile our steps start getting deeper on the dying land.\r\n\r\nThe sudden arrival of the sun\r\nprovokes a gentle breeze of hope\r\nas the dividing line\r\nbetween the dizzy present and the present past melts.\r\n\r\nAs we start to fall our love-mad plants avoid the smash.\r\nsuccessfully they reach the surface.\r\nthe sun welcomes them.\r\n\r\nIt’s time to grow more life.\r\n\r\n\r\nWords\r\n\r\nWords\r\nwhich sound like dogs,\r\nfiery tied-up dogs\r\nbarking in the middle of the night\r\nawaking you,\r\nalarming your already\r\nrestless soul\r\nso hungry for a good sleep.\r\n\r\nAnd then silence,\r\nunbearable emptiness,\r\nloud silence\r\nthat awakes \r\nthe now baby-like sleeping dogs\r\nwhile you long,\r\nyou long to hear those words.\r\n\r\nBut those words\r\nand the mouth that awakes them\r\nare fast asleep\r\nexhausted by the arduous task\r\nof bringing together\r\nnight\r\nand day…\r\n\r\nMystical glow\r\n\r\nA colossal shadow\r\non its last metamorphic phase\r\nrests on the façade\r\nof a house\r\nhold.\r\n\r\nSeemingly hostile\r\nas the unknown\r\ntends to look,\r\nas the sometimes unwelcome\r\nnight.\r\n\r\nIt’s eyes still closed\r\nawaiting patiently\r\nsome kind of acknowledgement\r\nfrom the one\r\namong the crowd\r\nthat like a herd of soulless sheep\r\npasses it by\r\nhardly noticing it,\r\nunaware\r\nof its actual\r\nbi-dimensional limitation.\r\n\r\n\r\n\r\nAnd I,\r\nby magical coincidence\r\nlocate its existence\r\nwhich shoots sharp\r\nbut inoffensive arrows\r\nwhich strike\r\nmy most vulnerable asset,\r\nmy innocent\r\nbut always alert\r\nconscience.\r\n\r\nA powerful\r\nand throbbing connection\r\nthat will not subside\r\nfor as long \r\nas curiosity\r\nsails the wildest rivers\r\nof my very existence.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nSunday\r\n\r\nAnother day with a borrowed sun\r\nthe washing-line reveals its secrets.\r\n\r\nPolice cars  trying out brand new alarm-clocks.\r\nTrees cheer them up from the pavement\r\nwatched by lions of stone\r\nbored by the history of time.\r\n\r\nOblivious passers-by,\r\nmen who dress like men\r\ndrinking water from the gutter,\r\nscarecrows look envious at the washing-line.\r\n\r\nThe Sun rises in a fruitless attempt to fly\r\nand I find last night’s bill on the kitchen table.\r\n\r\nPharmacies are always shut\r\nwhen you\r\nneed them\r\nmost.\r\n\r\n\r\n\r\n\r\n\r\n\r\nThink twice\r\n\r\nThe silence between thunders,\r\nthe darkness between lightnings,\r\nthe Sky looks like a balloon \r\ninflated to the limit.\r\n\r\nThe pressure of your actions,\r\na box full of gun powder,\r\nit’d take just one frightened spark\r\nto blow it all away.\r\n\r\nI know you\r\ndon’t’ mean to be\r\nmean\r\nbut words,\r\nwords sometimes hurt.\r\n\r\nEven if they hurt\r\nin silence.\r\n\r\nThink twice\r\nabout what you are\r\ngoing to say\r\nnext.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nBecause\r\n\r\n\r\nWhat made me leave the road\r\nto my already set\r\ndestination.\r\n\r\nWhy did I have to listen\r\nto your words\r\nand find them refreshingly revealing.\r\n\r\nHow can I have found\r\nso much sense\r\nin your creed,\r\nyour hired principles,\r\nyour self-explanatory \r\nspiritual nakedness.\r\n\r\nWhy did you have to play\r\nthat instrument\r\nof remorseless torture.\r\n\r\nYour singular voice,\r\nwhich like the burden\r\nof a heavy rusty carriage\r\npulled by fresh horses\r\ngave me an unsolicited gift\r\nto a more advanced stage\r\nof the road.\r\n\r\nWhy did you show\r\nso much\r\ninterest in my silent shouts.\r\n\r\nYou made me feel\r\nso human,\r\nso hopelessly\r\nhuman."
      ],
      publish_year: [2000],
      first_publish_year: 2000
    },
    {
      title_suggest: "Ancient Ways",
      edition_key: ["OL8088345M"],
      cover_i: 667084,
      isbn: ["0875420907", "9780875420905"],
      has_fulltext: true,
      text: [
        "OL8088345M",
        "0875420907",
        "9780875420905",
        "Dan & Pauline Campanelli",
        "ancientwaysrecla00camp",
        "OL2859889A",
        "Reclaimiing the  Pagan Tradition (Llewellyn's Practical Magick Series)",
        "Ancient Ways",
        "In library",
        "Magic",
        "Accessible book",
        "Religious calendars",
        "Rituals",
        "Protected DAISY",
        "Paganism",
        "Neopaganism",
        "/works/OL8541178W",
        "Llewellyn Publications",
        "Intricate and lacy designs etched in frost on the window panes frame a scene rendered in shades of gray, of horses in a snow storm, as the winter sun rises just a bright spot in a lead colored sky."
      ],
      author_name: ["Dan & Pauline Campanelli"],
      ia_loaded_id: ["ancientwaysrecla00camp"],
      seed: [
        "/books/OL8088345M",
        "/works/OL8541178W",
        "/subjects/paganism",
        "/subjects/rituals",
        "/subjects/magic",
        "/subjects/neopaganism",
        "/subjects/religious_calendars",
        "/subjects/protected_daisy",
        "/subjects/in_library",
        "/authors/OL2859889A"
      ],
      ia: ["ancientwaysrecla00camp"],
      author_key: ["OL2859889A"],
      subject: [
        "In library",
        "Magic",
        "Accessible book",
        "Religious calendars",
        "Rituals",
        "Protected DAISY",
        "Paganism",
        "Neopaganism"
      ],
      title: "Ancient Ways",
      lending_identifier_s: "ancientwaysrecla00camp",
      ia_collection_s:
        "printdisabled;browserlending;china;inlibrary;internetarchivebooks",
      first_publish_year: 2002,
      type: "work",
      ebook_count_i: 1,
      printdisabled_s: "OL8088345M",
      ia_box_id: ["IA180101"],
      edition_count: 1,
      key: "/works/OL8541178W",
      id_goodreads: ["1178839"],
      public_scan_b: false,
      publisher: ["Llewellyn Publications"],
      language: ["eng"],
      last_modified_i: 1406589068,
      lending_edition_s: "OL8088345M",
      id_librarything: ["3121645"],
      cover_edition_key: "OL8088345M",
      first_sentence: [
        "Intricate and lacy designs etched in frost on the window panes frame a scene rendered in shades of gray, of horses in a snow storm, as the winter sun rises just a bright spot in a lead colored sky."
      ],
      publish_year: [2002],
      publish_date: ["September 1, 2002"]
    }
  ]
});

export const detailPayload = () => ({
  description: {
    type: "/type/text",
    value:
      "STEP INTO A UNIVERSE OF DARING ADVENTURE, THRILLING POWER, AND MULTIPLE LONDONS.\r\n\r\nKell is one of the last travelers--magicians with a rare, coveted ability to travel between parallel universes connected by one magic city.\r\n\r\nThere's Grey London, dirty and boring, without any magic, and with one mad king--George III. Red London, where life and magic are revered--and where Kell was raised alongside Rhy Maresh, the roguish heir to a flourishing empire. White London--a place where people fight to control magic and the magic fights back, draining the city to its very bones. And once upon a time, there was Black London. But no one speaks of that now.\r\n\r\nOfficially, Kell is the Red Traveler, ambassador of the Maresh Empire, carrying the monthly correspondences between the royals of each London. Unofficially, Kell is a smuggler, servicing people willing to pay for even the smallest glimpses of a world they'll never see. It's a defiant hobby with dangerous consequences, which Kell is now seeing firsthand.\r\n\r\nFleeing into Grey London, Kell runs into Delilah Bard, a cutpurse with lofty aspirations. She first robs him, then saves him from a deadly enemy, and finally forces Kell to spirit  her to another world for a proper adventure.\r\n\r\nNow perilous magic is afoot, and treachery lurks at every turn. To save all of the worlds, they'll first need to stay alive.\r\n\r\nThis description comes from the publisher. *A Darker Shade of Magic* is the first book of the Shades of Magic trilogy."
  },
  created: {
    type: "/type/datetime",
    value: "2016-04-12T15:32:29.747514"
  },
  title: "A darker shade of magic",
  covers: [7410930],
  last_modified: {
    type: "/type/datetime",
    value: "2017-10-30T00:59:47.992289"
  },
  latest_revision: 9,
  key: "/works/OL17332803W",
  authors: [
    {
      type: {
        key: "/type/author_role"
      },
      author: {
        key: "/authors/OL6979295A"
      }
    }
  ],
  type: {
    key: "/type/work"
  },
  revision: 9
});
